Crack stitching
LogicalError/realtime-CSG-for-unity pull request #372
Opened 2022-12-07 14:35 UTC by Eideren

# Crack Stitching
Introduces a toggle to the model inspector UI which, once toggled on, fixes cracks appearing through generated geometry. It does so asynchronously to prevent interrupting the user while he's working.

See [discussion on discord](https://discord.com/channels/531067645433348106/531080244472315965/1048040793526517820) for further informations.

## Inspector
![image](https://user-images.githubusercontent.com/5742236/206205550-a6952d16-1e59-481f-96c6-0a259d87d290.png)
## Result
![image](https://user-images.githubusercontent.com/5742236/206205435-0aeff616-dd96-4aa7-93ee-e00d3a3bd72e.png)

2022-12-07 14:43 UTC, Eideren commented on Plugins/Editor/Scripts/Control/Helpers/CracksStitching.cs
> +            }
Small issue right now is the fact that I'm not yet sure how to solve triangle winding order, so I'm adding triangles facing both sides. If you have a suggestion I am open to implement it.

2022-12-08 15:09 UTC, Eideren commented
This issue doesn't appear *only* around t-junctions, see this case where multiple white pixels peek through two edges that should be touching:
![image](https://user-images.githubusercontent.com/5742236/206444273-40f5b443-db9b-46bf-be82-345fc8aeaeed.png)
It's not caused by the rasterization process either as getting closer does show a multi-pixel wide crack.

> an image comparison with wireframe on would help a bit with making it more apparent exactly what is being done.
Sure, edited the post to add one in.

Also, the logs for how long auto lightmap gen and stitching took are a bit too spam-y, could we do something about that ? 
Maybe log a warning for auto lightmap gen if it takes a significant amount of time since that's a blocking operation and users might become frustrated waiting for editor response when moving things around. Stitching isn't really blocking so not sure there even is a need to log it ?

2022-12-10 16:24 UTC, Eideren commented
Regarding my last complaint about duration logging, I replaced debug logging by unity's progress API.
![image](https://user-images.githubusercontent.com/5742236/206864840-12cd79f3-b781-4aa2-8312-2f05a0cb17b2.png)
![image](https://user-images.githubusercontent.com/5742236/206864790-7078eb9f-5136-4dad-a3ae-f2571f649b74.png)

2022-12-19 03:35 UTC, Gawidev commented
Currently in a very good spot, this feature is really amazing and RCSG will benefit greatly from it. 
Only small issue discovered when playing around with it is relating to surfaces set to non-visible, they currently seem to get in the way of the crack detection doing its job properly, sometimes filling them up in a broken manner.

2022-12-23 22:09 UTC, Eideren commented
I'm still looking into @Gawidev's issue, I have a fix - just have to iron out a couple of bugs and with the holidays and all I don't have a lot of time to go through it.

2023-01-08 17:35 UTC, Eideren commented
There we go, this commit should fix those issues. 
PR ready for further review/merge.

2023-01-08 20:37 UTC, Kerfuffles requested changes
Usings should be outside of any namespace. Additionally, `using static` will not compile on versions of Unity that don't have the C# 6 update.

2023-01-08 20:42 UTC, Kerfuffles commented on Plugins/Editor/Scripts/Control/Helpers/CracksStitching.cs
> +                    debug?.LogWarning($"For edge {thisEdge}, closest match ({bestMatch.edge}) did not satisfy {nameof(maxDist)} constraint {bestMatch.dist}/{maxDist}");
Should be using `String.Combine` instead of string interpolation, as older versions of Unity do not support it.

2023-01-08 20:44 UTC, Kerfuffles commented on Plugins/Editor/Scripts/Control/Helpers/CracksStitching.cs
> +                var (           _, mappingB) = posToSubMesh[vertices[y]];
Anonymous variables aren't supported on versions previous to C# 6.

2023-01-08 20:48 UTC, Kerfuffles reviewed
Everything looks OK. Just need to make sure that there aren't any unsupported API or C# features  on older versions of Unity, until the oldest supported version by RCSG (5.6.4f1) is updated to 2019+. I didn't tag every single change, but its easy to find by checking changes on here.

2023-01-09 16:41 UTC, Gawidev commented
Hey sorry resident "I-break-stuff" worker here, a bit of extra testing done and I've run into a similar issue where hidden faces are being treated strangely by the crack detection, this case particularly when there are hidden faces with different shadow-receiving and shadow-casting settings. 

Should be reproducible by creating a box brush, then setting one surface to non-visible, and another one to non-visible + non-shadow-casting.

They seem to get merged into the same generated render mesh, which shouldn't be the case, iirc there should be up to 5 possible generated render meshes for the same material.
(vis/receiver/caster, vis/receiver, vis/caster, vis only, invis/caster)
(This is cause rcsg assumes hidden faces should only be taken into consideration if they cast shadows)

2023-07-27 20:04 UTC, Kerfuffles commented
Any updates? Would love to get around to merging this.

2023-08-03 09:02 UTC, Eideren commented
I *should* have some time to take a look at this again this week end, I'll keep you posted

2024-07-18 05:10 UTC, Eideren commented
Closing in favor of #399

2024-07-18 05:10 UTC, closed without merging